"""empty message

Revision ID: 2a85448e54fb
Revises: 6f9448935011
Create Date: 2021-06-15 15:24:39.901352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a85448e54fb'
down_revision = '6f9448935011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bookTitle', sa.String(length=180), nullable=False),
    sa.Column('authorName', sa.String(length=80), nullable=False),
    sa.Column('bookType', sa.String(length=40), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Books')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Books',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Books_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('bookTitle', sa.VARCHAR(length=180), autoincrement=False, nullable=False),
    sa.Column('authorName', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('bookType', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Books_pkey')
    )
    op.drop_table('books')
    # ### end Alembic commands ###
