"""empty message

Revision ID: 6f9448935011
Revises: 
Create Date: 2021-06-15 13:47:54.081341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f9448935011'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bookTitle', sa.String(length=180), nullable=False),
    sa.Column('authorName', sa.String(length=80), nullable=False),
    sa.Column('bookType', sa.String(length=40), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Books')
    # ### end Alembic commands ###
